-- Backfill listing.model using the same keyword map as ModelNormalizer.java
-- Idempotent: only touches rows whose stored model still equals the raw title.
UPDATE listing
SET model = CASE
    WHEN title ~* '(^|[^a-z0-9])Golf\s*7($|[^a-z0-9])' THEN 'Golf 7'
    WHEN title ~* '(^|[^a-z0-9])Golf\s*8($|[^a-z0-9])' THEN 'Golf 8'
    WHEN title ~* '(^|[^a-z0-9])Golf($|[^a-z0-9])' THEN 'Golf'
    WHEN title ~* '(^|[^a-z0-9])Passat($|[^a-z0-9])' THEN 'Passat'
    WHEN title ~* '(^|[^a-z0-9])Polo($|[^a-z0-9])' THEN 'Polo'
    WHEN title ~* '(^|[^a-z0-9])Tiguan($|[^a-z0-9])' THEN 'Tiguan'
    WHEN title ~* '(^|[^a-z0-9])Touareg($|[^a-z0-9])' THEN 'Touareg'
    WHEN title ~* '(^|[^a-z0-9])Touran($|[^a-z0-9])' THEN 'Touran'
    WHEN title ~* '(^|[^a-z0-9])Arteon($|[^a-z0-9])' THEN 'Arteon'
    WHEN title ~* '(^|[^a-z0-9])T-Cross($|[^a-z0-9])' THEN 'T-Cross'
    WHEN title ~* '(^|[^a-z0-9])T-Roc($|[^a-z0-9])' THEN 'T-Roc'
    WHEN title ~* '(^|[^a-z0-9])Up($|[^a-z0-9])' THEN 'Up'
    WHEN title ~* '(^|[^a-z0-9])Caddy($|[^a-z0-9])' THEN 'Caddy'
    WHEN title ~* '(^|[^a-z0-9])Transporter($|[^a-z0-9])' THEN 'Transporter'
    WHEN title ~* '(^|[^a-z0-9])Amarok($|[^a-z0-9])' THEN 'Amarok'
    WHEN title ~* '(^|[^a-z0-9])Scirocco($|[^a-z0-9])' THEN 'Scirocco'
    WHEN title ~* '(^|[^a-z0-9])Beetle($|[^a-z0-9])' THEN 'Beetle'
    WHEN title ~* '(^|[^a-z0-9])Jetta($|[^a-z0-9])' THEN 'Jetta'
    WHEN title ~* '(^|[^a-z0-9])e-tron($|[^a-z0-9])' THEN 'e-tron'
    WHEN title ~* '(^|[^a-z0-9])Q8($|[^a-z0-9])' THEN 'Q8'
    WHEN title ~* '(^|[^a-z0-9])Q7($|[^a-z0-9])' THEN 'Q7'
    WHEN title ~* '(^|[^a-z0-9])Q5($|[^a-z0-9])' THEN 'Q5'
    WHEN title ~* '(^|[^a-z0-9])Q3($|[^a-z0-9])' THEN 'Q3'
    WHEN title ~* '(^|[^a-z0-9])Q2($|[^a-z0-9])' THEN 'Q2'
    WHEN title ~* '(^|[^a-z0-9])SQ5($|[^a-z0-9])' THEN 'SQ5'
    WHEN title ~* '(^|[^a-z0-9])A8($|[^a-z0-9])' THEN 'A8'
    WHEN title ~* '(^|[^a-z0-9])A7($|[^a-z0-9])' THEN 'A7'
    WHEN title ~* '(^|[^a-z0-9])A6($|[^a-z0-9])' THEN 'A6'
    WHEN title ~* '(^|[^a-z0-9])A5($|[^a-z0-9])' THEN 'A5'
    WHEN title ~* '(^|[^a-z0-9])A4($|[^a-z0-9])' THEN 'A4'
    WHEN title ~* '(^|[^a-z0-9])A3($|[^a-z0-9])' THEN 'A3'
    WHEN title ~* '(^|[^a-z0-9])A2($|[^a-z0-9])' THEN 'A2'
    WHEN title ~* '(^|[^a-z0-9])A1($|[^a-z0-9])' THEN 'A1'
    WHEN title ~* '(^|[^a-z0-9])TT($|[^a-z0-9])' THEN 'TT'
    WHEN title ~* '(^|[^a-z0-9])R8($|[^a-z0-9])' THEN 'R8'
    WHEN title ~* '(^|[^a-z0-9])RS($|[^a-z0-9])' THEN 'RS'
    WHEN title ~* '(^|[^a-z0-9])X7($|[^a-z0-9])' THEN 'X7'
    WHEN title ~* '(^|[^a-z0-9])X6($|[^a-z0-9])' THEN 'X6'
    WHEN title ~* '(^|[^a-z0-9])X5($|[^a-z0-9])' THEN 'X5'
    WHEN title ~* '(^|[^a-z0-9])X4($|[^a-z0-9])' THEN 'X4'
    WHEN title ~* '(^|[^a-z0-9])X3($|[^a-z0-9])' THEN 'X3'
    WHEN title ~* '(^|[^a-z0-9])X2($|[^a-z0-9])' THEN 'X2'
    WHEN title ~* '(^|[^a-z0-9])X1($|[^a-z0-9])' THEN 'X1'
    WHEN title ~* '(^|[^a-z0-9])M5($|[^a-z0-9])' THEN 'M5'
    WHEN title ~* '(^|[^a-z0-9])M4($|[^a-z0-9])' THEN 'M4'
    WHEN title ~* '(^|[^a-z0-9])M3($|[^a-z0-9])' THEN 'M3'
    WHEN title ~* '(^|[^a-z0-9])M2($|[^a-z0-9])' THEN 'M2'
    WHEN title ~* '(^|[^a-z0-9])Z4($|[^a-z0-9])' THEN 'Z4'
    WHEN title ~* '(^|[^a-z0-9])i8($|[^a-z0-9])' THEN 'i8'
    WHEN title ~* '(^|[^a-z0-9])i3($|[^a-z0-9])' THEN 'i3'
    WHEN title ~* '(^|[^a-z0-9])GLA($|[^a-z0-9])' THEN 'GLA'
    WHEN title ~* '(^|[^a-z0-9])GLB($|[^a-z0-9])' THEN 'GLB'
    WHEN title ~* '(^|[^a-z0-9])GLC($|[^a-z0-9])' THEN 'GLC'
    WHEN title ~* '(^|[^a-z0-9])GLE($|[^a-z0-9])' THEN 'GLE'
    WHEN title ~* '(^|[^a-z0-9])GLK($|[^a-z0-9])' THEN 'GLK'
    WHEN title ~* '(^|[^a-z0-9])CLA($|[^a-z0-9])' THEN 'CLA'
    WHEN title ~* '(^|[^a-z0-9])CLS($|[^a-z0-9])' THEN 'CLS'
    WHEN title ~* '(^|[^a-z0-9])Vito($|[^a-z0-9])' THEN 'Vito'
    WHEN title ~* '(^|[^a-z0-9])Sprinter($|[^a-z0-9])' THEN 'Sprinter'
    WHEN title ~* '(^|[^a-z0-9])Octavia($|[^a-z0-9])' THEN 'Octavia'
    WHEN title ~* '(^|[^a-z0-9])Superb($|[^a-z0-9])' THEN 'Superb'
    WHEN title ~* '(^|[^a-z0-9])Fabia($|[^a-z0-9])' THEN 'Fabia'
    WHEN title ~* '(^|[^a-z0-9])Rapid($|[^a-z0-9])' THEN 'Rapid'
    WHEN title ~* '(^|[^a-z0-9])Kodiaq($|[^a-z0-9])' THEN 'Kodiaq'
    WHEN title ~* '(^|[^a-z0-9])Karoq($|[^a-z0-9])' THEN 'Karoq'
    WHEN title ~* '(^|[^a-z0-9])Scala($|[^a-z0-9])' THEN 'Scala'
    WHEN title ~* '(^|[^a-z0-9])Yeti($|[^a-z0-9])' THEN 'Yeti'
    WHEN title ~* '(^|[^a-z0-9])Enyaq($|[^a-z0-9])' THEN 'Enyaq'
    WHEN title ~* '(^|[^a-z0-9])Roomster($|[^a-z0-9])' THEN 'Roomster'
    WHEN title ~* '(^|[^a-z0-9])Altea($|[^a-z0-9])' THEN 'Altea'
    WHEN title ~* '(^|[^a-z0-9])Tucson($|[^a-z0-9])' THEN 'Tucson'
    WHEN title ~* '(^|[^a-z0-9])Santa\s*Fe($|[^a-z0-9])' THEN 'Santa Fe'
    WHEN title ~* '(^|[^a-z0-9])Kona($|[^a-z0-9])' THEN 'Kona'
    WHEN title ~* '(^|[^a-z0-9])Elantra($|[^a-z0-9])' THEN 'Elantra'
    WHEN title ~* '(^|[^a-z0-9])i40($|[^a-z0-9])' THEN 'i40'
    WHEN title ~* '(^|[^a-z0-9])i30($|[^a-z0-9])' THEN 'i30'
    WHEN title ~* '(^|[^a-z0-9])i20($|[^a-z0-9])' THEN 'i20'
    WHEN title ~* '(^|[^a-z0-9])i10($|[^a-z0-9])' THEN 'i10'
    WHEN title ~* '(^|[^a-z0-9])Getz($|[^a-z0-9])' THEN 'Getz'
    WHEN title ~* '(^|[^a-z0-9])ix20($|[^a-z0-9])' THEN 'ix20'
    WHEN title ~* '(^|[^a-z0-9])Sportage($|[^a-z0-9])' THEN 'Sportage'
    WHEN title ~* '(^|[^a-z0-9])Sorento($|[^a-z0-9])' THEN 'Sorento'
    WHEN title ~* '(^|[^a-z0-9])Ceed($|[^a-z0-9])' THEN 'Ceed'
    WHEN title ~* '(^|[^a-z0-9])Rio($|[^a-z0-9])' THEN 'Rio'
    WHEN title ~* '(^|[^a-z0-9])Picanto($|[^a-z0-9])' THEN 'Picanto'
    WHEN title ~* '(^|[^a-z0-9])Stonic($|[^a-z0-9])' THEN 'Stonic'
    WHEN title ~* '(^|[^a-z0-9])Niro($|[^a-z0-9])' THEN 'Niro'
    WHEN title ~* '(^|[^a-z0-9])Seltos($|[^a-z0-9])' THEN 'Seltos'
    WHEN title ~* '(^|[^a-z0-9])Corsa($|[^a-z0-9])' THEN 'Corsa'
    WHEN title ~* '(^|[^a-z0-9])Astra($|[^a-z0-9])' THEN 'Astra'
    WHEN title ~* '(^|[^a-z0-9])Insignia($|[^a-z0-9])' THEN 'Insignia'
    WHEN title ~* '(^|[^a-z0-9])Mokka($|[^a-z0-9])' THEN 'Mokka'
    WHEN title ~* '(^|[^a-z0-9])Crossland($|[^a-z0-9])' THEN 'Crossland'
    WHEN title ~* '(^|[^a-z0-9])Grandland($|[^a-z0-9])' THEN 'Grandland'
    WHEN title ~* '(^|[^a-z0-9])Zafira($|[^a-z0-9])' THEN 'Zafira'
    WHEN title ~* '(^|[^a-z0-9])Vivaro($|[^a-z0-9])' THEN 'Vivaro'
    WHEN title ~* '(^|[^a-z0-9])Captur($|[^a-z0-9])' THEN 'Captur'
    WHEN title ~* '(^|[^a-z0-9])Clio($|[^a-z0-9])' THEN 'Clio'
    WHEN title ~* '(^|[^a-z0-9])Megane($|[^a-z0-9])' THEN 'Megane'
    WHEN title ~* '(^|[^a-z0-9])Scenic($|[^a-z0-9])' THEN 'Scenic'
    WHEN title ~* '(^|[^a-z0-9])Kadjar($|[^a-z0-9])' THEN 'Kadjar'
    WHEN title ~* '(^|[^a-z0-9])Koleos($|[^a-z0-9])' THEN 'Koleos'
    WHEN title ~* '(^|[^a-z0-9])Talisman($|[^a-z0-9])' THEN 'Talisman'
    WHEN title ~* '(^|[^a-z0-9])Symbol($|[^a-z0-9])' THEN 'Symbol'
    WHEN title ~* '(^|[^a-z0-9])Focus($|[^a-z0-9])' THEN 'Focus'
    WHEN title ~* '(^|[^a-z0-9])Fiesta($|[^a-z0-9])' THEN 'Fiesta'
    WHEN title ~* '(^|[^a-z0-9])Mondeo($|[^a-z0-9])' THEN 'Mondeo'
    WHEN title ~* '(^|[^a-z0-9])Kuga($|[^a-z0-9])' THEN 'Kuga'
    WHEN title ~* '(^|[^a-z0-9])EcoSport($|[^a-z0-9])' THEN 'EcoSport'
    WHEN title ~* '(^|[^a-z0-9])Puma($|[^a-z0-9])' THEN 'Puma'
    WHEN title ~* '(^|[^a-z0-9])Transit($|[^a-z0-9])' THEN 'Transit'
    WHEN title ~* '(^|[^a-z0-9])Ranger($|[^a-z0-9])' THEN 'Ranger'
    WHEN title ~* '(^|[^a-z0-9])3008($|[^a-z0-9])' THEN '3008'
    WHEN title ~* '(^|[^a-z0-9])5008($|[^a-z0-9])' THEN '5008'
    WHEN title ~* '(^|[^a-z0-9])2008($|[^a-z0-9])' THEN '2008'
    WHEN title ~* '(^|[^a-z0-9])308($|[^a-z0-9])' THEN '308'
    WHEN title ~* '(^|[^a-z0-9])208($|[^a-z0-9])' THEN '208'
    WHEN title ~* '(^|[^a-z0-9])508($|[^a-z0-9])' THEN '508'
    WHEN title ~* '(^|[^a-z0-9])Partner($|[^a-z0-9])' THEN 'Partner'
    WHEN title ~* '(^|[^a-z0-9])407($|[^a-z0-9])' THEN '407'
    WHEN title ~* '(^|[^a-z0-9])C3($|[^a-z0-9])' THEN 'C3'
    WHEN title ~* '(^|[^a-z0-9])C4($|[^a-z0-9])' THEN 'C4'
    WHEN title ~* '(^|[^a-z0-9])C5($|[^a-z0-9])' THEN 'C5'
    WHEN title ~* '(^|[^a-z0-9])C1($|[^a-z0-9])' THEN 'C1'
    WHEN title ~* '(^|[^a-z0-9])Berlingo($|[^a-z0-9])' THEN 'Berlingo'
    WHEN title ~* '(^|[^a-z0-9])500($|[^a-z0-9])' THEN '500'
    WHEN title ~* '(^|[^a-z0-9])Punto($|[^a-z0-9])' THEN 'Punto'
    WHEN title ~* '(^|[^a-z0-9])Tipo($|[^a-z0-9])' THEN 'Tipo'
    WHEN title ~* '(^|[^a-z0-9])Doblo($|[^a-z0-9])' THEN 'Doblo'
    WHEN title ~* '(^|[^a-z0-9])Panda($|[^a-z0-9])' THEN 'Panda'
    WHEN title ~* '(^|[^a-z0-9])Ducato($|[^a-z0-9])' THEN 'Ducato'
    WHEN title ~* '(^|[^a-z0-9])Ibiza($|[^a-z0-9])' THEN 'Ibiza'
    WHEN title ~* '(^|[^a-z0-9])Leon($|[^a-z0-9])' THEN 'Leon'
    WHEN title ~* '(^|[^a-z0-9])Arona($|[^a-z0-9])' THEN 'Arona'
    WHEN title ~* '(^|[^a-z0-9])Ateca($|[^a-z0-9])' THEN 'Ateca'
    WHEN title ~* '(^|[^a-z0-9])Tarraco($|[^a-z0-9])' THEN 'Tarraco'
    WHEN title ~* '(^|[^a-z0-9])Alhambra($|[^a-z0-9])' THEN 'Alhambra'
    WHEN title ~* '(^|[^a-z0-9])Toledo($|[^a-z0-9])' THEN 'Toledo'
    WHEN title ~* '(^|[^a-z0-9])Cupra($|[^a-z0-9])' THEN 'Cupra'
    WHEN title ~* '(^|[^a-z0-9])Formentor($|[^a-z0-9])' THEN 'Formentor'
    WHEN title ~* '(^|[^a-z0-9])Corolla($|[^a-z0-9])' THEN 'Corolla'
    WHEN title ~* '(^|[^a-z0-9])Yaris($|[^a-z0-9])' THEN 'Yaris'
    WHEN title ~* '(^|[^a-z0-9])RAV4($|[^a-z0-9])' THEN 'RAV4'
    WHEN title ~* '(^|[^a-z0-9])C-HR($|[^a-z0-9])' THEN 'C-HR'
    WHEN title ~* '(^|[^a-z0-9])Auris($|[^a-z0-9])' THEN 'Auris'
    WHEN title ~* '(^|[^a-z0-9])Avensis($|[^a-z0-9])' THEN 'Avensis'
    WHEN title ~* '(^|[^a-z0-9])Hilux($|[^a-z0-9])' THEN 'Hilux'
    WHEN title ~* '(^|[^a-z0-9])Prius($|[^a-z0-9])' THEN 'Prius'
    WHEN title ~* '(^|[^a-z0-9])Qashqai($|[^a-z0-9])' THEN 'Qashqai'
    WHEN title ~* '(^|[^a-z0-9])X-Trail($|[^a-z0-9])' THEN 'X-Trail'
    WHEN title ~* '(^|[^a-z0-9])Juke($|[^a-z0-9])' THEN 'Juke'
    WHEN title ~* '(^|[^a-z0-9])Micra($|[^a-z0-9])' THEN 'Micra'
    WHEN title ~* '(^|[^a-z0-9])Leaf($|[^a-z0-9])' THEN 'Leaf'
    WHEN title ~* '(^|[^a-z0-9])Navara($|[^a-z0-9])' THEN 'Navara'
    WHEN title ~* '(^|[^a-z0-9])XC40($|[^a-z0-9])' THEN 'XC40'
    WHEN title ~* '(^|[^a-z0-9])XC60($|[^a-z0-9])' THEN 'XC60'
    WHEN title ~* '(^|[^a-z0-9])XC90($|[^a-z0-9])' THEN 'XC90'
    WHEN title ~* '(^|[^a-z0-9])V40($|[^a-z0-9])' THEN 'V40'
    WHEN title ~* '(^|[^a-z0-9])V60($|[^a-z0-9])' THEN 'V60'
    WHEN title ~* '(^|[^a-z0-9])V90($|[^a-z0-9])' THEN 'V90'
    WHEN title ~* '(^|[^a-z0-9])S60($|[^a-z0-9])' THEN 'S60'
    WHEN title ~* '(^|[^a-z0-9])S90($|[^a-z0-9])' THEN 'S90'
    WHEN title ~* '(^|[^a-z0-9])Cayenne($|[^a-z0-9])' THEN 'Cayenne'
    WHEN title ~* '(^|[^a-z0-9])Macan($|[^a-z0-9])' THEN 'Macan'
    WHEN title ~* '(^|[^a-z0-9])Panamera($|[^a-z0-9])' THEN 'Panamera'
    WHEN title ~* '(^|[^a-z0-9])911($|[^a-z0-9])' THEN '911'
    WHEN title ~* '(^|[^a-z0-9])Boxster($|[^a-z0-9])' THEN 'Boxster'
    WHEN title ~* '(^|[^a-z0-9])Cayman($|[^a-z0-9])' THEN 'Cayman'
    WHEN title ~* '(^|[^a-z0-9])Cooper($|[^a-z0-9])' THEN 'Cooper'
    WHEN title ~* '(^|[^a-z0-9])CX-3($|[^a-z0-9])' THEN 'CX-3'
    WHEN title ~* '(^|[^a-z0-9])CX-5($|[^a-z0-9])' THEN 'CX-5'
    WHEN title ~* '(^|[^a-z0-9])CX-30($|[^a-z0-9])' THEN 'CX-30'
    WHEN title ~* '(^|[^a-z0-9])CX-60($|[^a-z0-9])' THEN 'CX-60'
    WHEN title ~* '(^|[^a-z0-9])Mazda\s*6($|[^a-z0-9])' THEN 'Mazda 6'
    WHEN title ~* '(^|[^a-z0-9])MX-5($|[^a-z0-9])' THEN 'MX-5'
    WHEN title ~* '(^|[^a-z0-9])Civic($|[^a-z0-9])' THEN 'Civic'
    WHEN title ~* '(^|[^a-z0-9])CR-V($|[^a-z0-9])' THEN 'CR-V'
    WHEN title ~* '(^|[^a-z0-9])HR-V($|[^a-z0-9])' THEN 'HR-V'
    WHEN title ~* '(^|[^a-z0-9])Jazz($|[^a-z0-9])' THEN 'Jazz'
    WHEN title ~* '(^|[^a-z0-9])Accord($|[^a-z0-9])' THEN 'Accord'
    WHEN title ~* '(^|[^a-z0-9])Defender($|[^a-z0-9])' THEN 'Defender'
    WHEN title ~* '(^|[^a-z0-9])Discovery($|[^a-z0-9])' THEN 'Discovery'
    WHEN title ~* '(^|[^a-z0-9])Range\s*Rover($|[^a-z0-9])' THEN 'Range Rover'
    WHEN title ~* '(^|[^a-z0-9])Freelander($|[^a-z0-9])' THEN 'Freelander'
    WHEN title ~* '(^|[^a-z0-9])Giulietta($|[^a-z0-9])' THEN 'Giulietta'
    WHEN title ~* '(^|[^a-z0-9])SL($|[^a-z0-9])' THEN 'SL'
    WHEN title ~* '(^|[^a-z0-9])S7($|[^a-z0-9])' THEN 'S7'
    WHEN title ~* '(^|[^a-z0-9])Seria\s*1($|[^a-z0-9])' THEN '1 Series'
    WHEN title ~* '(^|[^a-z0-9])Seria\s*2($|[^a-z0-9])' THEN '2 Series'
    WHEN title ~* '(^|[^a-z0-9])Seria\s*3($|[^a-z0-9])' THEN '3 Series'
    WHEN title ~* '(^|[^a-z0-9])Seria\s*4($|[^a-z0-9])' THEN '4 Series'
    WHEN title ~* '(^|[^a-z0-9])Seria\s*5($|[^a-z0-9])' THEN '5 Series'
    WHEN title ~* '(^|[^a-z0-9])Seria\s*6($|[^a-z0-9])' THEN '6 Series'
    WHEN title ~* '(^|[^a-z0-9])Seria\s*7($|[^a-z0-9])' THEN '7 Series'
    WHEN title ~* '(^|[^a-z0-9])Seria\s*8($|[^a-z0-9])' THEN '8 Series'
    WHEN title ~* '(^|[^a-z0-9])116($|[^a-z0-9])' THEN '1 Series'
    WHEN title ~* '(^|[^a-z0-9])118($|[^a-z0-9])' THEN '1 Series'
    WHEN title ~* '(^|[^a-z0-9])120($|[^a-z0-9])' THEN '1 Series'
    WHEN title ~* '(^|[^a-z0-9])F20($|[^a-z0-9])' THEN '1 Series'
    WHEN title ~* '(^|[^a-z0-9])F21($|[^a-z0-9])' THEN '1 Series'
    WHEN title ~* '(^|[^a-z0-9])316($|[^a-z0-9])' THEN '3 Series'
    WHEN title ~* '(^|[^a-z0-9])318($|[^a-z0-9])' THEN '3 Series'
    WHEN title ~* '(^|[^a-z0-9])320($|[^a-z0-9])' THEN '3 Series'
    WHEN title ~* '(^|[^a-z0-9])330($|[^a-z0-9])' THEN '3 Series'
    WHEN title ~* '(^|[^a-z0-9])F30($|[^a-z0-9])' THEN '3 Series'
    WHEN title ~* '(^|[^a-z0-9])F31($|[^a-z0-9])' THEN '3 Series'
    WHEN title ~* '(^|[^a-z0-9])F34($|[^a-z0-9])' THEN '3 Series GT'
    WHEN title ~* '(^|[^a-z0-9])F35($|[^a-z0-9])' THEN '3 Series'
    WHEN title ~* '(^|[^a-z0-9])G20($|[^a-z0-9])' THEN '3 Series'
    WHEN title ~* '(^|[^a-z0-9])418($|[^a-z0-9])' THEN '4 Series'
    WHEN title ~* '(^|[^a-z0-9])420($|[^a-z0-9])' THEN '4 Series'
    WHEN title ~* '(^|[^a-z0-9])420d($|[^a-z0-9])' THEN '4 Series'
    WHEN title ~* '(^|[^a-z0-9])430($|[^a-z0-9])' THEN '4 Series'
    WHEN title ~* '(^|[^a-z0-9])F32($|[^a-z0-9])' THEN '4 Series'
    WHEN title ~* '(^|[^a-z0-9])F36($|[^a-z0-9])' THEN '4 Series GC'
    WHEN title ~* '(^|[^a-z0-9])518($|[^a-z0-9])' THEN '5 Series'
    WHEN title ~* '(^|[^a-z0-9])520($|[^a-z0-9])' THEN '5 Series'
    WHEN title ~* '(^|[^a-z0-9])520d($|[^a-z0-9])' THEN '5 Series'
    WHEN title ~* '(^|[^a-z0-9])530($|[^a-z0-9])' THEN '5 Series'
    WHEN title ~* '(^|[^a-z0-9])535($|[^a-z0-9])' THEN '5 Series'
    WHEN title ~* '(^|[^a-z0-9])540($|[^a-z0-9])' THEN '5 Series'
    WHEN title ~* '(^|[^a-z0-9])F10($|[^a-z0-9])' THEN '5 Series'
    WHEN title ~* '(^|[^a-z0-9])F11($|[^a-z0-9])' THEN '5 Series'
    WHEN title ~* '(^|[^a-z0-9])G30($|[^a-z0-9])' THEN '5 Series'
    WHEN title ~* '(^|[^a-z0-9])M550i($|[^a-z0-9])' THEN '5 Series'
    WHEN title ~* '(^|[^a-z0-9])628($|[^a-z0-9])' THEN '6 Series'
    WHEN title ~* '(^|[^a-z0-9])630($|[^a-z0-9])' THEN '6 Series'
    WHEN title ~* '(^|[^a-z0-9])640($|[^a-z0-9])' THEN '6 Series'
    WHEN title ~* '(^|[^a-z0-9])640i($|[^a-z0-9])' THEN '6 Series'
    WHEN title ~* '(^|[^a-z0-9])650($|[^a-z0-9])' THEN '6 Series'
    WHEN title ~* '(^|[^a-z0-9])F06($|[^a-z0-9])' THEN '6 Series GC'
    WHEN title ~* '(^|[^a-z0-9])F12($|[^a-z0-9])' THEN '6 Series'
    WHEN title ~* '(^|[^a-z0-9])F13($|[^a-z0-9])' THEN '6 Series'
    WHEN title ~* '(^|[^a-z0-9])728($|[^a-z0-9])' THEN '7 Series'
    WHEN title ~* '(^|[^a-z0-9])730($|[^a-z0-9])' THEN '7 Series'
    WHEN title ~* '(^|[^a-z0-9])740($|[^a-z0-9])' THEN '7 Series'
    WHEN title ~* '(^|[^a-z0-9])740D($|[^a-z0-9])' THEN '7 Series'
    WHEN title ~* '(^|[^a-z0-9])750($|[^a-z0-9])' THEN '7 Series'
    WHEN title ~* '(^|[^a-z0-9])760($|[^a-z0-9])' THEN '7 Series'
    WHEN title ~* '(^|[^a-z0-9])G($|[^a-z0-9])' THEN 'G-Class'
    WHEN title ~* '(^|[^a-z0-9])C($|[^a-z0-9])' THEN 'C-Class'
    WHEN title ~* '(^|[^a-z0-9])E($|[^a-z0-9])' THEN 'E-Class'
    WHEN title ~* '(^|[^a-z0-9])S($|[^a-z0-9])' THEN 'S-Class'
    WHEN title ~* '(^|[^a-z0-9])A($|[^a-z0-9])' THEN 'A-Class'
    WHEN title ~* '(^|[^a-z0-9])B($|[^a-z0-9])' THEN 'B-Class'
    WHEN title ~* '(^|[^a-z0-9])W124($|[^a-z0-9])' THEN 'W124'
    WHEN title ~* '(^|[^a-z0-9])Cruze($|[^a-z0-9])' THEN 'Cruze'
    WHEN title ~* '(^|[^a-z0-9])Lynk($|[^a-z0-9])' THEN 'Lynk & Co'
    WHEN title ~* '(^|[^a-z0-9])E220d($|[^a-z0-9])' THEN 'E-Class'
    WHEN title ~* '(^|[^a-z0-9])XC\s*60($|[^a-z0-9])' THEN 'XC60'
    ELSE model
END
WHERE model = title;
